#Configuracion de la base de datos
server:
  port: 8080
  error:
    include-message: always

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8099/eureka/

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: empleados
          uri: lb://Empleados
          predicates:
            - Path=/Empleados/**
        - id: Horarios
          uri: lb://Horarios
          predicates:
            - Path=/Horarios/**
        - id: Reportes
          uri: lb://Reportes
          predicates:
            - Path=/Reportes/**