#Configuracion de la base de datos
server:
  port: 8091


spring:
  # Base de Datos
  dataSource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/mingeso
    username: postgres
    password: default

  #JPA
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        show_sql: true
        use_sql_comments: true
        format_sql: false

logging:
  pattern:
    console: '%d{yyyy-MM-dd HH:mm:ss} ${LOG_LEVEL_PATTERN:%5p} %m%n'
